M7R0
I4IsStronglyConnectedf*6#%"MG6(%$conG%"dG%"XG%"iG%"jG%"kG6"6"C'>8$%%trueG>8%-I-
RowDimensionG6$I(:-30526GQjn/Library/Frameworks/Maple.framework/Versions/2017/l
ib/maple.mlaF./%+modulenameGI.LinearAlgebraG6$%*protectedG%(_syslibG6#9$>8&-%$a
ddG6$)FA8)/FH;""!F4?(8'"""FNF4F2?(8(FNFNF4F2@$-%&evalbG6#/&FC6$FMFPFKC$>F1%&fal
seG[OF1F.F.F.F.,
I)IsNormalf*F$6#%"NG6"F.C$>F1-I*TransposeG6$I(:-30546GF9/F;F<F@-FS6#3-%%typeG6$
FA-.%'MatrixG6#%'squareG-I&EqualG6$I(:-30468GF9Fbo6$-I0delayDotProductG6$F>/F;I
,TypesettingG6$F>F?6$FAF1-Fdp6$F1FAF.F.F.F.,
I&mpolyf*6$F%F(6#%"pG6"F.C$>F1-I,DeterminantG6$I(:-30460GF9/F;F<6#-%'CYpolyG6$F
A9%O-%(collectG6$F1%"tGF.F.F.F.,
I#CYf*F^q6#%"KG6"F.C$>F1-%&solveG6$-F\qF\rFbrOF1F.F.F.F.,
I(hseriesf*6%F%%"nGF(6%%"HGF*Fjn6"F.C(>&F16#FK-I/IdentityMatrixG6$I(:-30484GF9/
F;F<6#F5>FCF^o?(F4FNFN,&9&FN!"#FNF2>&F16#F4)FAF4>&F16#,&FctFN!""FN,&)FAF\uFNFCF
]u?(F4FctFNF]rF2>Fft,(-Fdp6$FA&F16#,&F4FNF]uFNFN-Fdp6$FC&F16#,(F4FNFctF]uFNFNF]
u&F16#,&F4FNFctF]uFNOF1F.F.F.F.,
I&hpolyf*Fas6'FjnFdsF`qF*%$dimG6"F.C(>F1F^o>F4-F_s6%FAF]rFct>FPF5>FCFK?(FMFKFN,
&F]rFNF]uFNF2>FC,&FCFN*&&F46#FMFN)FbrFMFNFNO-I)MultiplyG6$I(:-30510GF9F^t6$,&F1
FN*&FbrFN-F[t6#FPFNF]uFCF.F.F.F.,
I'IsGoodf*F^q6&%"CG%"bG%"mGFbs6"F.C(>F17#-FcrF\r>FC-%%nopsG6#F1>F4F2>FMFK?(F.FN
FNF.3F42FMFCC$>FM,&FMFNFNFN>F4-FS6#3F42-%$absG6#,&-%&evalfG6#-F\z6#&F1FcwFNF]uF
N$FN!")OF4F.F.F.F.,
I&firstf*F^q6$%"fG%"vG6"F.C%>F1-%(unapplyGF\s>F4--%"DGF]y6#FNO-%'factorGFgtF.F.
F.F.,
I'CYpolyf*F^q6$F`q%"WG6"F.C%>F4Fjs>F1,*F4FN*&FAFNFbrFNF]u*&F^oFN)FbrF^wFNFN*&F4
FN)FbrF]rFNF]uOF1F.F.F.F.,
I#phf*FasF.6"F.-%&printG6#FivF.F.F.F.,
I&thilbf*Fas6*Fds%"LGF,F*F+Fjn%"sGFdv6"F.C'>F1Fiv>F47">8+F5?(FCFKFNF]rF2C%>FH&F
16#FC>8*-FE6$-FE6$&FHFW/FM;FNFj]l/FPFh^l>F47$-%#opGFgtFa^lOF4F.F.F.F.,
I#GKf*F^q6+%"AG%"qG%"rGFc]lF*FdxFbs%%pairGFdv6"F.C,>F1-I(AdjointG6$I(:-30432GF9
/F;F<Fiq>8,F5>F4-FE6$-FE6$&F16$FPF+/FP;FNF_`l/F+Fh`l>FC-%&rootsG6#F]s>FM-F\alFg
t>FHFK>Fa^lFK?(FPFNFN-F\yF_^lF2C$>Fj]l&FCF^x@$/&Fj]lFf[lFNC$>FH&Fj]l6#""#Fen?(F
PFNFN-F\yFcwF2C$>Fj]l&FMF^x@$FhalC$>Fa^lF\blFenO,&FHFNFa^lF]uF.F.F.F.,
I'mutatef*6$F%F\[l6,FdvF*F+Fjn%$newGFfr%"UG%"VG%"aGFcx6"F.C0>F1F5@$0F1-I0Column
DimensionG6$I(:-30444GF9F:F@OQ2error:~not~squareF.@$52F]rFK2F1F]rOQ6error:~inva
lid~vertexF.?(F4FNFNF1F2@$0&FA6$F4F4FKOQ4error:~not~looplessF.?(FCF^blFNF1F2?(F
4FNFN,&FCFNF]uFNF2@$30&FA6$F4FCFK0&FA6$FCF4FKOQ2error:~two-cyclesF.>FM-F[pF]y?(
F4FNFNF1F2?(FCFNFNF1F2>&FMF`el*&&FA6$F4F]rFN&FA6$F]rFCFN>FH,&FAFNFMFN>Fa^l-I*Su
bMatrixG6$I(:-30539GF9F:6%FHF]r;FNF1>Fj]l-Fefl6%FHFiflF]r>&FH6$F]rFifl-F_o6#Fj]
l>&FH6$FiflF]r-F_o6#Fa^l?(FCF^blFNF1F2?(F4FNFNF[elF2C%>F_`l&FHF`el>8-&FHFcel@$3
0F_`lFK0F]hlFK@%2F]hlF_`lC$>F[hl,&F_`lFNF]hlF]u>F^hlFKC$>F[hlFK>F^hl,&F]hlFNF_`
lF]uOFHF.F.F.F.,
I$facf*6#Fbs6&%$divG%#ndGF*Ffr6"F.C$@%/FAFK>FM7#7$FKFKC&>F1-I)divisorsG6$I&:-27
2GF9/F;I*numtheoryG6$F>F?F@>F4F[y>FMFh]l?(FCFNFN,&F4#FNF^blFhjlFNF2>FM7$-F]_lFc
w7$F^^l&F16#,(F4FNFCF]uFNFNOFMF.F.F.F.,
I'Upairsf*6#Fb]l60F^cl%#lsG%#nlGFbsF`clFcx%"cGF*F+F,Fjn%"xG%"yG%"zG6"F.C&>F1Fh]
l>FC-F\yF@?(FMFNFNFCF2C'>F4&FAFcw>FP-F^il6#&F4Ff[l>FH-F^il6#&F4F]bl>Fa^l-F^il6#
&F46#""$?(Fj]lFNFN-F\yF^xF2C$@$/&&FPFaglFf[lFK>Fh]m7$81FK?(F_`lFNFN-F\y6#FHF2C$
@$/&&FH6#F_`lFf[lFK>Fc^m7$80FK?(F]hlFNFN-F\yFfglF2C%@$/&&Fa^l6#F]hlFf[lFK>F^_m7
$8/FK>8.7%Fh]mFc^mF^_m>F17$-F]_lF]y-F]_l6#-I(permuteG6$I%:-53GF9/F;I)combinatG6
$F>F?6#Fd_mOF1F.F.F.F.,
I#mff*6&%"uGF\[l%"wG%$gamG6,%"PGFb]lF*Fd_l%#nrGF^clFjn%&mlistGF%%"BG6"F.C)@%/9'
FK>F17#7#FK>F1-I*partitionG6$I%:-52GF9/F;F``m6#Fcam>F4Fh]l?&FMF1F2C$>FPF`bl@$1F
PFa]m>F47$F\_l7$F[[m-F]_l6#7#-%$seqG6$FK/FC;FN,&Fa]mFNFPF]u>FH-Fa[mFgt>Fj]lFh]l
?&F]hlFHF2C)>F_`l7#-F[cm6$-F[pF`]m/FC;FN""%?(FCFNFNF\dmF2C)>Fa^l&F_`lF_^l>&Fa^l
6$FNFNFA>&Fa^l6$F^blF^blF]r>&Fa^l6$Fa]mFa]mFct>&Fa^l6$FNF^bl&&F]hlFf[lFf[l>&Fa^
l6$F^blFN&F^emF]bl@)/FCFNC&>&Fa^l6$FNFa]m&&F]hlF]blFf[l>&Fa^l6$Fa]mFN&FjemF]bl>
&Fa^l6$F^blFa]m&&F]hlF`]mFf[l>&Fa^l6$Fa]mF^bl&FcfmF]bl/FCF^blC&>FgemF^fm>F\fmFi
emF_fmFdfm/FCFa]mC&FfemF[fm>F`fmFgfm>FefmFbfmC&FjfmF[gmF^gmF_gm@$5555554-F"6#&F
_`l6#F\dm-F_p6$F[hm&F_`lF`]m-F_p6$F[hm&F_`lF]bl-F_p6$F[hm&F_`lFf[l-F_p6$F[hm-F_
o6#F_hm-F_p6$F[hm-F_o6#Fbhm-F_p6$F[hm-F_o6#Fehm>F_`l-%'subsopG6$/F\dm%%NULLGF_`
l@$55554-F"Fihm-F_p6$F_hmFbhm-F_p6$F_hmFehm-F_p6$F_hmF\im-F_p6$F_hmF`im>F_`l-Fd
im6$/Fa]mFgimF_`l@$554-F"F]im-F_p6$FbhmFehm-F_p6$FbhmF`im>F_`l-Fdim6$/F^blFgimF
_`l@$4-F"Faim>F_`l-Fdim6$/FNFgimF_`l>Fj]l7$-F]_lFagl-F]_lFd^mOFj]lF.F.F.F.,
I&mfindf*6'Fg`mF\[lFh`mFi`mF(60Ffr%"gG%"RG%$matG%$difG%$solGF*F+F,%"EG%%polyG%"
SGFc]lFb]l6"F.C%>F[^mFh]l>F1&-%(sortcycG6#9(6#,(FAFNF]rFNFctFN?(F4FKFNFcamF2C$>
FC-Fd`m6&FAF]rFctF4?&Fd_mF1F2?&FMFCF2C$>FH-%(msolverG6%Fd_mFMFh]n?&Fb_mFHF2-%&c
leanG6$FMFb_mF.F.F.F.,
I$cycf*6'F`qFb]lFbsF,F(6'%"TGF*Fc_lFd_lFcil6"F.C%>F1Fh]l?(F4FcamFNFctF2C&>FC&F]
rFgt>FM-%'expandG6#*&FAFNFCFN>FP-%'degreeGFcw@&/FPFh]n>F17$Fh_mFM1FPFh]n>F17$Fh
_m-F]_l6#-F[_n6'FMF]rFctF4Fh]nOF1F.F.F.F.,
I(sortcycf*6#%$degG6+F(Fbs%#rtG%"GGF[amF*Fh\n%&pandaGFg[m6"F.C*@%-Fgo6$FA%$oddG
>FC*$,&FNFNFbrF]uFa]m>FC*&F[bnFa]m,&FNFNFbrFNFN>F1,&FAFa]m-F^`nF_^lF]u>F4-%$max
G6$,&"#=FNFA!"$Fa]m>FM-%'getcycGF]y>FP-%&tableGF.?(FHFKFNF4F2>&FPF^^mFh]l?&Fa^l
FMF2C%>Fj]l-Fi_n6#*&Fa^lFNFCFN>F_`l-%&coeffG6$Fj]l)Fbr,&FAFa]mF]uFN@$31FKF_`l1F
_`lF4>&FPFd^m7$-F]_l6#FcdnFj]lOFPF.F.F.F.,
I'getcycf*6#F(6'%%listG%&polysG%%jcycGF+%"JG6"F.C&>F47$z)6#Fbr#FN"Fdt!FNz)Feen#
FN"F^bl!FN?(FMF^blFNFAF2C$>FC-I'invphiG6$I&:-280GF9/F;FbjlFcw?&FPFCF2>F47$F\_l-
I+cyclotomicG6$I&:-271GF9F^fn6$FPFbr>F1-F[_n6'FNF4-F\yFgtFNFAOF1F.F.F.F.,
I&cleanf*6$F%F_]n6.%%varsG%&rlistG%'qcheckG%#nSGFc]lF*Fd_lFg[mF\[lF]]n%"eGFb]l6
"F.C*>F1Fh]l>F4Fh]l>FCF2>FM-F\y6#F]r>Fb_m-%(convertG6$F]rF\en?&FPFb_mF2>F17$Fh_
m-%$lhsGF^x?(FHFNFNFMF2C%>FP&Fb_mF^^m>Fa^l-%$rhsGF^x@)1F^bl-F^`nFfgl>F4F[_l-Fgo
6$Fa^l%'RootOfG@$-Fgo6$Fa^l%*radalgnumGC&>F]hl7#-%*allvaluesGF^x?&Fd_mF]hlF2C$>
FihnFd_m-Fi^n6$FAFb_m>FCFZFen1F_inFK@%552Fa^lFK-Fgo6$Fa^l%(nonrealG-FS6#0Fa^l-I
&floorG6$F>F?FfglC$FbjnFenF`inC%>Fj]lFK?&F_`lF1F2C$>Fj]l-Fjcn6$Fa^lF_`l@$0Fj]lF
KFen@$Fj[o@'-Fgo6$Fj]lFcin@$-Fgo6$Fj]lFginC&Fiin?&Fd_mF]hlF2C$F_jnF`jnFbjnFen55
2Fj]lFK-Fgo6$-F_[oFaglFjjn-FS6#0Fj]lFj\oC$FbjnFenF`in@$FC@%/FMFjfn-%(MakeMatG6%
FAF1F4-F]]lFajnF.F.F.F.,
I(MakeMatf*6%F%F_clFi\n6$FjnF[[l6"F.C$@%/F_]nFh]l>F1FAC$>F4-Fa[l6$FA-F]_lF\hn>F
1-F46#-F]_l6#Fct@$-F"F]y-F]]lF]yF.F.F.F.,
I(msolverf*6%F`qF%F(6'F[]nF]]nF,F\]nFdgn6"F.C&>FMFh]l>F1,&-F\q6$F]rFctFNFAF]u@$
/-Fjcn6$F1)Fbr,&FctFa]mFdtFNFKC$>F4<#-F]_l6#-%%ceqsG6%F1F]rFct>FM7$F[[m-F[sFgtO
FMF.F.F.F.,
I%ceqsf*6%F[]nF%F(6$F]]nF,6"F.C%>F17#-FhzFf_o?(F4Fa]mFN-F_[o6#,$Fct#Fa]mF^blF2>
F17$Fh_m-Fjcn6$FA)Fbr,&FctFa]mF4F]uOF1F.F.F.F.
